version: '3'
services:

  # genesis node
  tm-ndid:
    image: ndidplatform/tendermint:latest
    environment:
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
    command: 
      - genesis
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci-ndid:${ABCI_PORT:-46000}
    ports:
      - 45000:${TM_RPC_PORT:-45000}
      - 47000:${TM_P2P_PORT:-47000}
    networks:
      - ndidplatform
    depends_on:
      - abci-ndid

  # secondary nodes
  tm-idp:
    image: ndidplatform/tendermint:latest
    environment:
      - SEED_HOSTNAME=tm-ndid
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
    command: 
      - secondary
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci-idp:${ABCI_PORT:-46000}
    ports:
      - 45001:${TM_RPC_PORT:-45000}
      - 47001:${TM_P2P_PORT:-47000}
    networks:
      - ndidplatform
    depends_on:
      - tm-ndid
      - abci-idp
  tm-rp:
    image: ndidplatform/tendermint:latest
    environment:
      - SEED_HOSTNAME=tm-ndid
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
    command: 
      - secondary
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci-rp:${ABCI_PORT:-46000}
    ports:
      - 45002:${TM_RPC_PORT:-45000}
      - 47002:${TM_P2P_PORT:-47000}
    networks:
      - ndidplatform
    depends_on:
      - tm-ndid
      - abci-rp
  tm-as:
    image: ndidplatform/tendermint:latest
    environment:
      - SEED_HOSTNAME=tm-ndid
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
    command: 
      - secondary
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci-as:${ABCI_PORT:-46000}
    ports:
      - 45003:${TM_RPC_PORT:-45000}
      - 47003:${TM_P2P_PORT:-47000}
    networks:
      - ndidplatform
    depends_on:
      - tm-ndid
      - abci-as

  # abci containers
  abci-ndid:
    image: ndidplatform/abci:latest
    command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
    networks:
      - ndidplatform  
  abci-idp:
    image: ndidplatform/abci:latest
    command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
    networks:
      - ndidplatform
  abci-rp:
    image: ndidplatform/abci:latest
    command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
    networks:
      - ndidplatform
  abci-as:
    image: ndidplatform/abci:latest
    command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
    networks:
      - ndidplatform

networks:
  ndidplatform: