version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start TM and ABCI container
          command: |
            docker-compose -f docker-compose.yml up -d
      - run: sleep 30
      - run:
          name: Start API container
          command: |
            docker-compose -f docker-compose.api.yml up -d
      - run: sleep 30
      - run: docker ps 
