version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: mkdir test-result
      - setup_remote_docker
      - run:
          name: Start TM and ABCI container
          command: |
            docker-compose -f docker-compose.yml up -d
      - run:
          name: Start API container
          command: |
            docker-compose -f docker-compose.api.yml up -d
      - run: npm install
      - run: sleep 30
      - run:
          name: Start NDID Data Request Test 
          command: |
            docker-compose -f docker-compose-dataRequest.yml up --abort-on-container-exit
      - store_test_results:
          path: ./test-result
      - store_artifacts:
          path: .
          destination: project
